name: Blueprints
version: 1.0.0
description: Blueprints plugin to build custom UI for Flextype.
icon:
  name: card-list
  set: bootstrap
author:
  name: Sergey Romanenko
  email: sergey.romanenko@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/blueprints
documentation: https://github.com/flextype-plugins/blueprints
changelog: https://github.com/flextype-plugins/blueprints/blob/master/CHANGELOG.md
bugs: https://github.com/flextype-plugins/blueprints/issues
license: MIT

dependencies:
  flextype: 0.9.16
  twig: '>=2.0.0'
