# enabled: true or false to disable the plugin
enabled: true

# Blueprint plugin priority
priority: 45

# place to load
load_on_site: true
load_on_admin: true

blocks:
  - Anchor
  - Alert
  - Button
  - Divider
  - Group
  - Heading
  - Html
  - Image
  - InputText
  - InputEmail
  - InputPassword
  - InputTextarea
  - InputHidden
  - InputNumber
  - InputDateTimePicker
  - InputEditor
  - InputTags
  - InputSelect
  - InputSelectRoutable
  - InputSelectVisibility
  - InputSelectTemplate
  - InputReset
  - InputButton
  - InputSubmit
